In [1]:
# Data Visualization
# BTech Computer Science Stream , January 2025
# Week 3: NumPy basics and vectorized computation Exercises
# Name: Param Shah , Reg No: 240905320 , Date: 27/1/2025 

In [3]:
# Question 1

In [25]:
import numpy as np

arr = np.random.randint(1, 51, size=(3, 4))
print(arr)

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

total_sum = np.sum(arr)
row_sums = np.sum(arr, axis=1)

print("\nSum of all elements:", total_sum)
print("Sum of each row:", row_sums)

arr = arr.reshape(2, 6)
print("\nReshaped 2x6 Array:")
print(arr)

[[27  8  4  9]
 [21 50 44 20]
 [23 42 11 38]]

Mean: 24.75
Median: 22.0
Standard Deviation: 14.928300863349005

Sum of all elements: 297
Sum of each row: [ 48 135 114]

Reshaped 2x6 Array:
[[27  8  4  9 21 50]
 [44 20 23 42 11 38]]


In [27]:
# Question 2

In [29]:
import numpy as np

arr1 = np.random.randint(1,10,size=(3,3))
arr2 = np.random.randint(1,10,size=(3,3))

print(arr1)
print("\n")
print(arr2)
print("\n")
print("Sum\n")
print(arr1 + arr2)
print("\n")
print("Difference\n")
print(arr1 - arr2)
print("\n")
print("Element wise Multiplication\n")
print(arr1 * arr2)
print("\n")
print("Dot Multiplication\n")
print(np.dot(arr1,arr2))
transpose_arr1 = np.transpose(arr1)
transpose_arr2 = np.transpose(arr2)

print("\nTranspose of Matrix arr1:")
print(transpose_arr1)
print("\nTranspose of Matrix arr2:")
print(transpose_arr2)

det_arr1 = np.linalg.det(arr1)
det_arr2 = np.linalg.det(arr2)
if det_arr1 != 0:
    inverse_arr1 = np.linalg.inv(arr1)
    print("\nInverse of Matrix arr1:")
    print(inverse_arr1)
else:
    print("\nMatrix arr1 is singular and does not have an inverse.")

if det_arr2 != 0:
    inverse_arr2 = np.linalg.inv(arr2)
    print("\nInverse of Matrix arr2:")
    print(inverse_arr2)
else:
    print("\nMatrix arr2 is singular and does not have an inverse.")

[[7 4 3]
 [2 3 9]
 [3 1 7]]


[[7 7 3]
 [7 5 1]
 [3 7 6]]


Sum

[[14 11  6]
 [ 9  8 10]
 [ 6  8 13]]


Difference

[[ 0 -3  0]
 [-5 -2  8]
 [ 0 -6  1]]


Element wise Multiplication

[[49 28  9]
 [14 15  9]
 [ 9  7 42]]


Dot Multiplication

[[86 90 43]
 [62 92 63]
 [49 75 52]]

Transpose of Matrix arr1:
[[7 2 3]
 [4 3 1]
 [3 9 7]]

Transpose of Matrix arr2:
[[7 7 3]
 [7 5 7]
 [3 1 6]]

Inverse of Matrix arr1:
[[ 0.10434783 -0.2173913   0.23478261]
 [ 0.11304348  0.34782609 -0.49565217]
 [-0.06086957  0.04347826  0.11304348]]

Inverse of Matrix arr2:
[[-2.3  2.1  0.8]
 [ 3.9 -3.3 -1.4]
 [-3.4  2.8  1.4]]
